-- Create restaurant_tables table
CREATE TABLE IF NOT EXISTS public.restaurant_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    floor INTEGER NOT NULL CHECK (floor IN (1, 2)),
    min_pax INTEGER NOT NULL DEFAULT 2,
    max_pax INTEGER NOT NULL DEFAULT 4,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'maintenance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add table_id to bookings table
ALTER TABLE public.bookings 
ADD COLUMN IF NOT EXISTS table_id BIGINT REFERENCES public.restaurant_tables(id);

-- Create index for faster lookup
CREATE INDEX IF NOT EXISTS idx_bookings_table_id ON public.bookings(table_id);
CREATE INDEX IF NOT EXISTS idx_restaurant_tables_floor ON public.restaurant_tables(floor);
CREATE INDEX IF NOT EXISTS idx_restaurant_tables_pax ON public.restaurant_tables(min_pax, max_pax);

-- Enable RLS (Row Level Security) if not already enabled (optional but recommended)
ALTER TABLE public.restaurant_tables ENABLE ROW LEVEL SECURITY;

-- Policy: Allow full access to authenticated users (admin) and read access to public (if needed for booking logic later, mostly admin for now)
-- Adjust based on your Auth setup. Assuming simple setup for now or standard Supabase anon/service_role.
-- For now allowing anon read for booking logic if needed, but mostly admin.
CREATE POLICY "Allow public read access" ON public.restaurant_tables FOR SELECT USING (true);
CREATE POLICY "Allow authenticated full access" ON public.restaurant_tables FOR ALL USING (true);
